apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-charts.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "helm-charts.name" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP