plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.cloud.tools.jib' version '3.4.0'
}

group = 'com.kubernetes'
version = '0.0.1'
description = 'Demo project for Kubernetes'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

jib {

	from {
		image = "docker://k8s-demo/openjdk17:1.0"
	}

	to {
		image = "k8s-demo/enterprise-kubernetes-demo:1.0"
	}

	container {
		mainClass = "com.kubernetes.KubernetesApplication"

		ports = ["8080"]
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

// ======== Custom Tasks - DAM ===========

tasks.register("buildImage") {
	group = "kubernetes"
	description = "Build container image using Jib"
	dependsOn("jibBuildTar")
}

tasks.register("loadImage", Exec) {

	group = "kubernetes"
	description = "Load container image into Rancher Desktop containerd"

	dependsOn("buildImage")

	commandLine "nerdctl",
			"-n", "k8s.io",
			"load",
			"-i", "build/jib-image.tar"
}

tasks.register("deployHelm", Exec) {

	group = "kubernetes"
	description = "Deploy Helm chart"

	dependsOn("loadImage")

	commandLine "helm",
			"upgrade",
			"--install",
			"enterprise-kubernetes-demo",
			"../helm-charts",
			"-n", "k8s-demo",
			"--create-namespace"
}

tasks.register("restartDeployment", Exec) {

	group = "kubernetes"
	description = "Restart Kubernetes deployment"

	dependsOn("deployHelm")

	commandLine "kubectl",
			"rollout",
			"restart",
			"deployment",
			"enterprise-kubernetes-demo-helm-charts",
			"-n",
			"k8s-demo"
}

tasks.register("deploy") {

	group = "kubernetes"
	description = "Full Kubernetes deployment pipeline"

	dependsOn("restartDeployment")
}